
//input ports
add mapped point no_value sel
add mapped point no_value src0[31]
add mapped point no_value src0[30]
add mapped point no_value src0[29]
add mapped point no_value src0[28]
add mapped point no_value src0[27]
add mapped point no_value src0[26]
add mapped point no_value src0[25]
add mapped point no_value src0[24]
add mapped point no_value src0[23]
add mapped point no_value src0[22]
add mapped point no_value src0[21]
add mapped point no_value src0[20]
add mapped point no_value src0[19]
add mapped point no_value src0[18]
add mapped point no_value src0[17]
add mapped point no_value src0[16]
add mapped point no_value src0[15]
add mapped point no_value src0[14]
add mapped point no_value src0[13]
add mapped point no_value src0[12]
add mapped point no_value src0[11]
add mapped point no_value src0[10]
add mapped point no_value src0[9]
add mapped point no_value src0[8]
add mapped point no_value src0[7]
add mapped point no_value src0[6]
add mapped point no_value src0[5]
add mapped point no_value src0[4]
add mapped point no_value src0[3]
add mapped point no_value src0[2]
add mapped point no_value src0[1]
add mapped point no_value src0[0]
add mapped point no_value src1[31]
add mapped point no_value src1[30]
add mapped point no_value src1[29]
add mapped point no_value src1[28]
add mapped point no_value src1[27]
add mapped point no_value src1[26]
add mapped point no_value src1[25]
add mapped point no_value src1[24]
add mapped point no_value src1[23]
add mapped point no_value src1[22]
add mapped point no_value src1[21]
add mapped point no_value src1[20]
add mapped point no_value src1[19]
add mapped point no_value src1[18]
add mapped point no_value src1[17]
add mapped point no_value src1[16]
add mapped point no_value src1[15]
add mapped point no_value src1[14]
add mapped point no_value src1[13]
add mapped point no_value src1[12]
add mapped point no_value src1[11]
add mapped point no_value src1[10]
add mapped point no_value src1[9]
add mapped point no_value src1[8]
add mapped point no_value src1[7]
add mapped point no_value src1[6]
add mapped point no_value src1[5]
add mapped point no_value src1[4]
add mapped point no_value src1[3]
add mapped point no_value src1[2]
add mapped point no_value src1[1]
add mapped point no_value src1[0]

//output ports
add mapped point no_value z[31]
add mapped point no_value z[30]
add mapped point no_value z[29]
add mapped point no_value z[28]
add mapped point no_value z[27]
add mapped point no_value z[26]
add mapped point no_value z[25]
add mapped point no_value z[24]
add mapped point no_value z[23]
add mapped point no_value z[22]
add mapped point no_value z[21]
add mapped point no_value z[20]
add mapped point no_value z[19]
add mapped point no_value z[18]
add mapped point no_value z[17]
add mapped point no_value z[16]
add mapped point no_value z[15]
add mapped point no_value z[14]
add mapped point no_value z[13]
add mapped point no_value z[12]
add mapped point no_value z[11]
add mapped point no_value z[10]
add mapped point no_value z[9]
add mapped point no_value z[8]
add mapped point no_value z[7]
add mapped point no_value z[6]
add mapped point no_value z[5]
add mapped point no_value z[4]
add mapped point no_value z[3]
add mapped point no_value z[2]
add mapped point no_value z[1]
add mapped point no_value z[0]

//inout ports




//Sequential Pins



//Black Boxes
