
//input ports
add mapped point no_value x[31]
add mapped point no_value x[30]
add mapped point no_value x[29]
add mapped point no_value x[28]
add mapped point no_value x[27]
add mapped point no_value x[26]
add mapped point no_value x[25]
add mapped point no_value x[24]
add mapped point no_value x[23]
add mapped point no_value x[22]
add mapped point no_value x[21]
add mapped point no_value x[20]
add mapped point no_value x[19]
add mapped point no_value x[18]
add mapped point no_value x[17]
add mapped point no_value x[16]
add mapped point no_value x[15]
add mapped point no_value x[14]
add mapped point no_value x[13]
add mapped point no_value x[12]
add mapped point no_value x[11]
add mapped point no_value x[10]
add mapped point no_value x[9]
add mapped point no_value x[8]
add mapped point no_value x[7]
add mapped point no_value x[6]
add mapped point no_value x[5]
add mapped point no_value x[4]
add mapped point no_value x[3]
add mapped point no_value x[2]
add mapped point no_value x[1]
add mapped point no_value x[0]
add mapped point no_value y[31]
add mapped point no_value y[30]
add mapped point no_value y[29]
add mapped point no_value y[28]
add mapped point no_value y[27]
add mapped point no_value y[26]
add mapped point no_value y[25]
add mapped point no_value y[24]
add mapped point no_value y[23]
add mapped point no_value y[22]
add mapped point no_value y[21]
add mapped point no_value y[20]
add mapped point no_value y[19]
add mapped point no_value y[18]
add mapped point no_value y[17]
add mapped point no_value y[16]
add mapped point no_value y[15]
add mapped point no_value y[14]
add mapped point no_value y[13]
add mapped point no_value y[12]
add mapped point no_value y[11]
add mapped point no_value y[10]
add mapped point no_value y[9]
add mapped point no_value y[8]
add mapped point no_value y[7]
add mapped point no_value y[6]
add mapped point no_value y[5]
add mapped point no_value y[4]
add mapped point no_value y[3]
add mapped point no_value y[2]
add mapped point no_value y[1]
add mapped point no_value y[0]

//output ports
add mapped point no_value z[31]
add mapped point no_value z[30]
add mapped point no_value z[29]
add mapped point no_value z[28]
add mapped point no_value z[27]
add mapped point no_value z[26]
add mapped point no_value z[25]
add mapped point no_value z[24]
add mapped point no_value z[23]
add mapped point no_value z[22]
add mapped point no_value z[21]
add mapped point no_value z[20]
add mapped point no_value z[19]
add mapped point no_value z[18]
add mapped point no_value z[17]
add mapped point no_value z[16]
add mapped point no_value z[15]
add mapped point no_value z[14]
add mapped point no_value z[13]
add mapped point no_value z[12]
add mapped point no_value z[11]
add mapped point no_value z[10]
add mapped point no_value z[9]
add mapped point no_value z[8]
add mapped point no_value z[7]
add mapped point no_value z[6]
add mapped point no_value z[5]
add mapped point no_value z[4]
add mapped point no_value z[3]
add mapped point no_value z[2]
add mapped point no_value z[1]
add mapped point no_value z[0]

//inout ports




//Sequential Pins



//Black Boxes
