
//input ports
add mapped point A[31] A[31]
add mapped point A[30] A[30]
add mapped point A[29] A[29]
add mapped point A[28] A[28]
add mapped point A[27] A[27]
add mapped point A[26] A[26]
add mapped point A[25] A[25]
add mapped point A[24] A[24]
add mapped point A[23] A[23]
add mapped point A[22] A[22]
add mapped point A[21] A[21]
add mapped point A[20] A[20]
add mapped point A[19] A[19]
add mapped point A[18] A[18]
add mapped point A[17] A[17]
add mapped point A[16] A[16]
add mapped point A[15] A[15]
add mapped point A[14] A[14]
add mapped point A[13] A[13]
add mapped point A[12] A[12]
add mapped point A[11] A[11]
add mapped point A[10] A[10]
add mapped point A[9] A[9]
add mapped point A[8] A[8]
add mapped point A[7] A[7]
add mapped point A[6] A[6]
add mapped point A[5] A[5]
add mapped point A[4] A[4]
add mapped point A[3] A[3]
add mapped point A[2] A[2]
add mapped point A[1] A[1]
add mapped point A[0] A[0]
add mapped point B[31] B[31]
add mapped point B[30] B[30]
add mapped point B[29] B[29]
add mapped point B[28] B[28]
add mapped point B[27] B[27]
add mapped point B[26] B[26]
add mapped point B[25] B[25]
add mapped point B[24] B[24]
add mapped point B[23] B[23]
add mapped point B[22] B[22]
add mapped point B[21] B[21]
add mapped point B[20] B[20]
add mapped point B[19] B[19]
add mapped point B[18] B[18]
add mapped point B[17] B[17]
add mapped point B[16] B[16]
add mapped point B[15] B[15]
add mapped point B[14] B[14]
add mapped point B[13] B[13]
add mapped point B[12] B[12]
add mapped point B[11] B[11]
add mapped point B[10] B[10]
add mapped point B[9] B[9]
add mapped point B[8] B[8]
add mapped point B[7] B[7]
add mapped point B[6] B[6]
add mapped point B[5] B[5]
add mapped point B[4] B[4]
add mapped point B[3] B[3]
add mapped point B[2] B[2]
add mapped point B[1] B[1]
add mapped point B[0] B[0]
add mapped point Op[3] Op[3]
add mapped point Op[2] Op[2]
add mapped point Op[1] Op[1]
add mapped point Op[0] Op[0]

//output ports
add mapped point Carryout Carryout
add mapped point Overflow Overflow
add mapped point Final_result[31] Final_result[31]
add mapped point Final_result[30] Final_result[30]
add mapped point Final_result[29] Final_result[29]
add mapped point Final_result[28] Final_result[28]
add mapped point Final_result[27] Final_result[27]
add mapped point Final_result[26] Final_result[26]
add mapped point Final_result[25] Final_result[25]
add mapped point Final_result[24] Final_result[24]
add mapped point Final_result[23] Final_result[23]
add mapped point Final_result[22] Final_result[22]
add mapped point Final_result[21] Final_result[21]
add mapped point Final_result[20] Final_result[20]
add mapped point Final_result[19] Final_result[19]
add mapped point Final_result[18] Final_result[18]
add mapped point Final_result[17] Final_result[17]
add mapped point Final_result[16] Final_result[16]
add mapped point Final_result[15] Final_result[15]
add mapped point Final_result[14] Final_result[14]
add mapped point Final_result[13] Final_result[13]
add mapped point Final_result[12] Final_result[12]
add mapped point Final_result[11] Final_result[11]
add mapped point Final_result[10] Final_result[10]
add mapped point Final_result[9] Final_result[9]
add mapped point Final_result[8] Final_result[8]
add mapped point Final_result[7] Final_result[7]
add mapped point Final_result[6] Final_result[6]
add mapped point Final_result[5] Final_result[5]
add mapped point Final_result[4] Final_result[4]
add mapped point Final_result[3] Final_result[3]
add mapped point Final_result[2] Final_result[2]
add mapped point Final_result[1] Final_result[1]
add mapped point Final_result[0] Final_result[0]
add mapped point Set Set

//inout ports




//Sequential Pins



//Black Boxes
