
//input ports
add mapped point no_value A[31]
add mapped point no_value A[30]
add mapped point no_value A[29]
add mapped point no_value A[28]
add mapped point no_value A[27]
add mapped point no_value A[26]
add mapped point no_value A[25]
add mapped point no_value A[24]
add mapped point no_value A[23]
add mapped point no_value A[22]
add mapped point no_value A[21]
add mapped point no_value A[20]
add mapped point no_value A[19]
add mapped point no_value A[18]
add mapped point no_value A[17]
add mapped point no_value A[16]
add mapped point no_value A[15]
add mapped point no_value A[14]
add mapped point no_value A[13]
add mapped point no_value A[12]
add mapped point no_value A[11]
add mapped point no_value A[10]
add mapped point no_value A[9]
add mapped point no_value A[8]
add mapped point no_value A[7]
add mapped point no_value A[6]
add mapped point no_value A[5]
add mapped point no_value A[4]
add mapped point no_value A[3]
add mapped point no_value A[2]
add mapped point no_value A[1]
add mapped point no_value A[0]
add mapped point no_value B[31]
add mapped point no_value B[30]
add mapped point no_value B[29]
add mapped point no_value B[28]
add mapped point no_value B[27]
add mapped point no_value B[26]
add mapped point no_value B[25]
add mapped point no_value B[24]
add mapped point no_value B[23]
add mapped point no_value B[22]
add mapped point no_value B[21]
add mapped point no_value B[20]
add mapped point no_value B[19]
add mapped point no_value B[18]
add mapped point no_value B[17]
add mapped point no_value B[16]
add mapped point no_value B[15]
add mapped point no_value B[14]
add mapped point no_value B[13]
add mapped point no_value B[12]
add mapped point no_value B[11]
add mapped point no_value B[10]
add mapped point no_value B[9]
add mapped point no_value B[8]
add mapped point no_value B[7]
add mapped point no_value B[6]
add mapped point no_value B[5]
add mapped point no_value B[4]
add mapped point no_value B[3]
add mapped point no_value B[2]
add mapped point no_value B[1]
add mapped point no_value B[0]
add mapped point no_value Op[3]
add mapped point no_value Op[2]
add mapped point no_value Op[1]
add mapped point no_value Op[0]

//output ports
add mapped point no_value Carryout
add mapped point no_value Overflow
add mapped point no_value Result[31]
add mapped point no_value Result[30]
add mapped point no_value Result[29]
add mapped point no_value Result[28]
add mapped point no_value Result[27]
add mapped point no_value Result[26]
add mapped point no_value Result[25]
add mapped point no_value Result[24]
add mapped point no_value Result[23]
add mapped point no_value Result[22]
add mapped point no_value Result[21]
add mapped point no_value Result[20]
add mapped point no_value Result[19]
add mapped point no_value Result[18]
add mapped point no_value Result[17]
add mapped point no_value Result[16]
add mapped point no_value Result[15]
add mapped point no_value Result[14]
add mapped point no_value Result[13]
add mapped point no_value Result[12]
add mapped point no_value Result[11]
add mapped point no_value Result[10]
add mapped point no_value Result[9]
add mapped point no_value Result[8]
add mapped point no_value Result[7]
add mapped point no_value Result[6]
add mapped point no_value Result[5]
add mapped point no_value Result[4]
add mapped point no_value Result[3]
add mapped point no_value Result[2]
add mapped point no_value Result[1]
add mapped point no_value Result[0]

//inout ports




//Sequential Pins



//Black Boxes
